[versions]
kotlin = "2.2.21"
dokka = "2.1.0"
vanniktech-maven-publish = "0.34.0"
opentest4j = "1.3.0"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-jvm = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }
opentest4j = { module = "org.opentest4j:opentest4j", version.ref = "opentest4j" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
vanniktech-maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech-maven-publish" }
